Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - email
      ######################################
      # 任意のEMAILから確認メールを送信したい場合は設定する
      ######################################
      #EmailConfiguration:
      #  EmailSendingAccount: "DEVELOPER"
      #  SourceArn: "arn:aws:ses:[ここにArn]:identity/[]"
      EmailVerificationMessage: ' 検証コードは {####} です。'
      EmailVerificationSubject: ' 検証コード'
      MfaConfiguration: "OFF"
      Policies:
        ######################################
        # パスワードポリシー
        ######################################
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: False
          RequireUppercase: true
      UserPoolName: ${self:provider.stage}-${self:custom.cognito-name}
      UsernameAttributes:
        - email
      Schema:
        #- Name : email
        #  Required: true
        #  Mutable: true
        - Name : given_name
          Required: true
          Mutable: true
          AttributeDataType: String
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 256
        - Name : family_name
          Required: true
          Mutable: true
          AttributeDataType: String
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 256
        - Name: admin
          Mutable: true
          Required: false
          AttributeDataType: Number
          NumberAttributeConstraints:
            MinValue: 0
            MaxValue: 999
          #StringAttributeConstraints:
          #  MaxLength: 2
          #  MinLength: 2
      #SchemaAttributes:
      #  - AttributeDataType: String
      #    DeveloperOnlyAttribute: false
      #    Mutable: true
      #    Name: given_name
      #    Required: true
      #    StringAttributeConstraints:
      #      MaxLength: '2048'
      #      MinLength: '0'
      #  - AttributeDataType: String
      #    DeveloperOnlyAttribute: false
      #    Mutable: true
      #    Name: family_name
      #    Required: true
      #    StringAttributeConstraints:
      #      MaxLength: '2048'
      #      MinLength: '0'

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:provider.stage}-${self:custom.cognito-name}Client
      ######################################
      # サポートする認証フロー
      ######################################
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      UserPoolId:
        Ref: CognitoUserPool

Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool
    Export:
      Name: ${self:provider.stage}-UserPoolId

  UserPoolIdArn:
    Value:  
      Fn::GetAtt: [CognitoUserPool, Arn]
    Export:
      Name: ${self:provider.stage}-UserPoolIdArn

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
    Export:
      Name: ${self:provider.stage}-UserPoolClientId